import os
import tempfile
import unittest
from pathlib import Path

from sparkdeck.envfile_settings import (
    EnvFileConflictError,
    SECRET_KEY_PATTERN,
    apply_env_updates,
    field_mapping,
    parse_env_file,
    resolve_control_updates,
)


SAMPLE = """# DSpark serving knobs — regenerated by start.sh
MAX_MODEL_LEN=262144
# MAX_NUM_SEQS=32
export SERVED_MODEL_NAME='org/model'  # name clients see

GPU_MEMORY_UTILIZATION=0.9
GPU_MEMORY_UTILIZATION_TEXT="0.92"
API_TOKEN=supersecret
garbage line without equals
"""


class ParseEnvFileTests(unittest.TestCase):
    def test_parse_orders_active_and_commented_entries(self):
        entries = parse_env_file(SAMPLE)

        self.assertEqual(
            [(entry["key"], entry["enabled"], entry["line"]) for entry in entries],
            [
                ("MAX_MODEL_LEN", True, 2),
                ("MAX_NUM_SEQS", False, 3),
                ("SERVED_MODEL_NAME", True, 4),
                ("GPU_MEMORY_UTILIZATION", True, 6),
                ("GPU_MEMORY_UTILIZATION_TEXT", True, 7),
                ("API_TOKEN", True, 8),
            ],
        )

    def test_parse_keeps_raw_quoted_values(self):
        entries = {entry["key"]: entry for entry in parse_env_file(SAMPLE)}

        self.assertEqual(entries["SERVED_MODEL_NAME"]["value"], "'org/model'")
        self.assertEqual(entries["GPU_MEMORY_UTILIZATION_TEXT"]["value"], '"0.92"')

    def test_parse_strips_inline_comment_from_unquoted_value(self):
        entries = parse_env_file("MAX_MODEL_LEN=1024  # tokens\n")

        self.assertEqual(entries[0]["value"], "1024")

    def test_secret_key_pattern_matches_credential_substrings(self):
        # Substring matching is intentionally broad: MONKEY contains KEY.
        for key in ("API_TOKEN", "HF_TOKEN", "MY_SECRET", "admin_password", "SSH_KEY", "MONKEY"):
            self.assertTrue(SECRET_KEY_PATTERN.search(key), key)
        for key in ("MAX_MODEL_LEN", "SERVED_MODEL_NAME", "GPU_MEMORY_UTILIZATION"):
            self.assertFalse(SECRET_KEY_PATTERN.search(key), key)


class ApplyEnvUpdatesTests(unittest.TestCase):
    def setUp(self):
        self.dir = tempfile.TemporaryDirectory()
        self.addCleanup(self.dir.cleanup)
        self.path = Path(self.dir.name) / ".env.test"
        self.path.write_text(SAMPLE, encoding="utf-8")

    def _write_and_read(self, updates, **kwargs):
        apply_env_updates(self.path, updates, **kwargs)
        return self.path.read_text(encoding="utf-8")

    def test_empty_updates_leave_the_file_byte_identical(self):
        result = self._write_and_read({})

        self.assertEqual(result, SAMPLE)

    def test_update_active_value_preserves_inline_comment_and_export(self):
        result = self._write_and_read({"SERVED_MODEL_NAME": "'org/new'"})

        self.assertIn("export SERVED_MODEL_NAME='org/new'  # name clients see\n", result)

    def test_plain_string_enables_commented_key_in_place(self):
        result = self._write_and_read({"MAX_NUM_SEQS": "16"})

        lines = result.splitlines()
        self.assertEqual(lines[2], "MAX_NUM_SEQS=16")
        self.assertNotIn("# MAX_NUM_SEQS", result)

    def test_disable_comments_the_entry_out_in_place(self):
        result = self._write_and_read({
            "GPU_MEMORY_UTILIZATION": {"value": None, "enabled": False},
        })

        lines = result.splitlines()
        self.assertEqual(lines[5], "# GPU_MEMORY_UTILIZATION=0.9")

    def test_disable_with_new_value_updates_and_comments(self):
        result = self._write_and_read({
            "GPU_MEMORY_UTILIZATION": {"value": "0.8", "enabled": False},
        })

        self.assertIn("# GPU_MEMORY_UTILIZATION=0.8\n", result)

    def test_plain_null_deletes_an_active_entry(self):
        result = self._write_and_read({"API_TOKEN": None})

        self.assertNotIn("API_TOKEN", result)

    def test_plain_null_rejects_commented_or_missing_keys(self):
        with self.assertRaises(ValueError):
            apply_env_updates(self.path, {"MAX_NUM_SEQS": None})
        with self.assertRaises(ValueError):
            apply_env_updates(self.path, {"MISSING": None})

    def test_new_key_appends_at_end_of_file(self):
        result = self._write_and_read({"MTP_NUM_TOKENS": "3"})

        self.assertTrue(result.endswith("MTP_NUM_TOKENS=3\n"))
        self.assertTrue(result.startswith("# DSpark serving knobs"))

    def test_new_disabled_key_appends_commented(self):
        result = self._write_and_read({
            "DRAFT_MODEL": {"value": "org/draft", "enabled": False},
        })

        self.assertTrue(result.endswith("# DRAFT_MODEL=org/draft\n"))

    def test_write_creates_bak_copy_of_the_original(self):
        self._write_and_read({"MAX_MODEL_LEN": "131072"})

        backup = Path(f"{self.path}.bak")
        self.assertTrue(backup.exists())
        self.assertEqual(backup.read_text(encoding="utf-8"), SAMPLE)

    def test_result_reports_updated_deleted_enabled_and_new_mtime(self):
        before = os.stat(self.path).st_mtime
        result = apply_env_updates(self.path, {
            "MAX_NUM_SEQS": "16",
            "API_TOKEN": None,
            "MAX_MODEL_LEN": "131072",
        })

        self.assertEqual(result["path"], str(self.path))
        self.assertEqual(sorted(result["updated"]), ["MAX_MODEL_LEN", "MAX_NUM_SEQS"])
        self.assertEqual(result["deleted"], ["API_TOKEN"])
        self.assertEqual(result["enabled"], ["MAX_NUM_SEQS"])
        self.assertGreaterEqual(result["mtime"], before)

    def test_stale_mtime_raises_conflict_and_leaves_file_untouched(self):
        with self.assertRaises(EnvFileConflictError):
            apply_env_updates(
                self.path, {"MAX_MODEL_LEN": "1"}, expected_mtime=12345.0,
            )

        self.assertEqual(self.path.read_text(encoding="utf-8"), SAMPLE)

    def test_current_mtime_is_accepted(self):
        mtime = os.stat(self.path).st_mtime
        result = self._write_and_read(
            {"MAX_MODEL_LEN": "131072"}, expected_mtime=mtime,
        )

        self.assertIn("MAX_MODEL_LEN=131072", result)

    def test_validation_rejects_bad_key_names(self):
        for key in ("1BAD", "HAS-DASH", "HAS SPACE", ""):
            with self.assertRaises(ValueError, msg=key):
                apply_env_updates(self.path, {key: "x"})

    def test_validation_rejects_newlines_and_nul_in_values(self):
        for value in ("a\rb", "a\nb", "a\x00b"):
            with self.assertRaises(ValueError, msg=repr(value)):
                apply_env_updates(self.path, {"MAX_MODEL_LEN": value})

    def test_validation_rejects_oversize_values(self):
        with self.assertRaises(ValueError):
            apply_env_updates(self.path, {"MAX_MODEL_LEN": "x" * (8 * 1024 + 1)})

    def test_validation_rejects_oversize_files(self):
        self.path.write_text(
            SAMPLE + "#" + "x" * (256 * 1024), encoding="utf-8",
        )
        with self.assertRaises(ValueError):
            apply_env_updates(self.path, {"MAX_MODEL_LEN": "1"})

    def test_validation_rejects_too_many_updates(self):
        updates = {f"VAR_{index}": "1" for index in range(129)}
        with self.assertRaises(ValueError):
            apply_env_updates(self.path, updates)

    def test_validation_rejects_relative_paths(self):
        with self.assertRaises(ValueError):
            apply_env_updates("relative.env", {})

    def test_validation_rejects_malformed_update_objects(self):
        with self.assertRaises(ValueError):
            apply_env_updates(self.path, {"MAX_MODEL_LEN": {"value": 5, "enabled": True}})
        with self.assertRaises(ValueError):
            apply_env_updates(self.path, {"MAX_MODEL_LEN": {"value": "5"}})
        with self.assertRaises(ValueError):
            apply_env_updates(self.path, {"MAX_MODEL_LEN": 5})


class FieldMappingTests(unittest.TestCase):
    def test_first_candidate_present_in_file_wins(self):
        entries = parse_env_file(SAMPLE)

        mapping = field_mapping(entries)

        self.assertEqual(mapping["gpu_memory_utilization"], "GPU_MEMORY_UTILIZATION")
        self.assertEqual(mapping["served_model_name"], "SERVED_MODEL_NAME")
        self.assertEqual(mapping["context_window"], "MAX_MODEL_LEN")
        # Commented-out keys still back their control.
        self.assertEqual(mapping["max_concurrency"], "MAX_NUM_SEQS")

    def test_controls_without_a_backing_key_are_omitted(self):
        entries = parse_env_file("MAX_MODEL_LEN=1024\n")

        self.assertEqual(field_mapping(entries), {"context_window": "MAX_MODEL_LEN"})

    def test_text_fallback_when_primary_key_is_absent(self):
        entries = parse_env_file("GPU_MEMORY_UTILIZATION_TEXT=0.92\n")

        self.assertEqual(
            field_mapping(entries)["gpu_memory_utilization"],
            "GPU_MEMORY_UTILIZATION_TEXT",
        )


class ResolveControlUpdatesTests(unittest.TestCase):
    def test_maps_submitted_controls_to_env_keys(self):
        entries = parse_env_file(SAMPLE)

        updates = resolve_control_updates(
            {"context_window": 131072, "max_concurrency": 16},
            0.85,
            "org/new",
            entries,
        )

        self.assertEqual(updates, {
            "MAX_MODEL_LEN": "131072",
            "MAX_NUM_SEQS": "16",
            "GPU_MEMORY_UTILIZATION": "0.85",
            "SERVED_MODEL_NAME": "org/new",
        })

    def test_skips_none_and_empty_values(self):
        entries = parse_env_file(SAMPLE)

        updates = resolve_control_updates(
            {"context_window": None, "kv_cache_dtype": ""}, None, None, entries,
        )

        self.assertEqual(updates, {})

    def test_unmapped_control_raises_naming_the_control(self):
        entries = parse_env_file("MAX_MODEL_LEN=1024\n")

        with self.assertRaises(ValueError) as ctx:
            resolve_control_updates({"max_concurrency": 4}, None, None, entries)

        message = str(ctx.exception)
        self.assertIn("max_concurrency", message)
        self.assertIn("MAX_NUM_SEQS", message)

    def test_control_without_candidates_is_rejected(self):
        entries = parse_env_file(SAMPLE)

        with self.assertRaises(ValueError) as ctx:
            resolve_control_updates({"thinking_mode": "enabled"}, None, None, entries)

        self.assertIn("thinking_mode", str(ctx.exception))


if __name__ == "__main__":
    unittest.main()
