"""Settings edits for hook-backed external containers via a KEY=VALUE env file.

External lifecycle containers (labeled ``io.sparkdeck.start-command`` /
``io.sparkdeck.stop-command``) are regenerated by host scripts from an env
file named by the ``io.sparkdeck.env-file`` label. Instead of recreating the
container, SparkDeck edits that file in place — preserving comments, blank
lines, and ordering — and the user applies the change with the card's
existing stop/start hooks.

Update protocol for :func:`apply_env_updates` ``updates`` values:

- ``str``: set the key's value; a commented-out key is enabled in place; an
  unknown key is appended at the end of the file.
- ``None``: delete the key's line entirely.
- ``{"value": str | None, "enabled": bool}``: set the value (``None`` keeps
  the existing value text) and enable (uncomment) or disable (comment out in
  place) the entry; an unknown key is appended, commented when disabled.

When the file defines a key more than once, updates target the effective
occurrence — shell last-wins semantics: the last active assignment, or the
last commented occurrence when the key only appears commented out.
"""

from __future__ import annotations

import os
import re
import shutil
import stat
from pathlib import Path
from typing import Any

_KEY_NAME = re.compile(r"[A-Za-z_][A-Za-z0-9_]*")

# Entries whose key mentions a credential word are shown redacted in the UI
# (write-only overwrite) so saving settings never echoes secrets back.
SECRET_KEY_PATTERN = re.compile(r"(TOKEN|KEY|SECRET|PASSWORD)", re.IGNORECASE)

# Structured editor controls backed by env-file variables, in preference
# order: the first candidate present in the file (enabled or not) wins.
CONTROL_ENV_CANDIDATES: dict[str, tuple[str, ...]] = {
    "context_window": ("MAX_MODEL_LEN",),
    "max_concurrency": ("MAX_NUM_SEQS",),
    "max_num_batched_tokens": ("MAX_NUM_BATCHED_TOKENS",),
    "kv_cache_dtype": ("KV_CACHE_DTYPE",),
    "gpu_memory_utilization": (
        "GPU_MEMORY_UTILIZATION", "GPU_MEMORY_UTILIZATION_TEXT",
    ),
    "served_model_name": ("SERVED_MODEL_NAME",),
}

_MAX_FILE_BYTES = 256 * 1024
_MAX_ENTRIES = 512
_MAX_VALUE_BYTES = 8 * 1024
_MAX_UPDATES = 128

_ACTIVE_LINE = re.compile(
    r"^(?P<indent>\s*)(?P<export>export[ \t]+)?(?P<key>[A-Za-z_][A-Za-z0-9_]*)[ \t]*=",
)
_COMMENTED_LINE = re.compile(
    r"^(?P<indent>\s*)#[ \t]*(?P<export>export[ \t]+)?(?P<key>[A-Za-z_][A-Za-z0-9_]*)[ \t]*=",
)


class EnvFileConflictError(RuntimeError):
    """Raised when the env file changed on disk since it was read."""


def _split_value(raw: str) -> tuple[str, str]:
    """Split the text after ``=`` into (value, trailing inline comment).

    Quoted values keep their quotes and run to the closing quote; inside
    double quotes ``\\`` escapes the next character (so ``\\"`` does not end
    the value), while single quotes have no escapes. Unquoted values end at
    the first `` #`` comment marker. The raw text is never interpreted beyond
    that split.
    """
    text = raw.lstrip()
    if text[:1] == "'":
        closing = text.find("'", 1)
        if closing > 0:
            return text[: closing + 1], text[closing + 1 :]
        return text, ""
    if text[:1] == '"':
        index = 1
        while index < len(text):
            if text[index] == "\\":
                index += 2
                continue
            if text[index] == '"':
                return text[: index + 1], text[index + 1 :]
            index += 1
        return text, ""
    marker = re.search(r"\s+#", text)
    if marker:
        return text[: marker.start()], text[marker.start() :]
    return text, ""


def _entry_value(line: str, match: re.Match[str]) -> str:
    value, _comment = _split_value(line[match.end():])
    return value


def parse_env_file(text: str) -> list[dict[str, Any]]:
    """Parse KEY=VALUE lines (active and ``#``-commented) in file order.

    Returns entries ``{key, value, enabled, line}`` with 1-based line
    numbers. Values keep their raw text (quotes included); every other line
    is not an entry and is preserved verbatim by :func:`apply_env_updates`.
    """
    entries: list[dict[str, Any]] = []
    for line_no, line in enumerate(text.splitlines(), start=1):
        enabled = True
        match = _ACTIVE_LINE.match(line)
        if match is None:
            match = _COMMENTED_LINE.match(line)
            enabled = False
        if match is None:
            continue
        entries.append({
            "key": match.group("key"),
            "value": _entry_value(line, match),
            "enabled": enabled,
            "line": line_no,
        })
    return entries


def _validate_value(key: str, value: str) -> None:
    if any(character in value for character in "\r\n\x00"):
        raise ValueError(
            f"environment variable {key} cannot contain a newline or NUL"
        )
    if len(value.encode("utf-8")) > _MAX_VALUE_BYTES:
        raise ValueError(f"environment variable {key} exceeds 8 KiB")


def _normalized_updates(
    updates: dict[str, Any],
) -> dict[str, tuple[str | None, bool | None]]:
    """Validate updates into ``{key: (value, enabled)}``; value None deletes."""
    if not isinstance(updates, dict):
        raise ValueError("updates must be an object")
    if len(updates) > _MAX_UPDATES:
        raise ValueError(f"cannot update more than {_MAX_UPDATES} variables at once")
    normalized: dict[str, tuple[str | None, bool | None]] = {}
    for key, raw in updates.items():
        if not isinstance(key, str) or not _KEY_NAME.fullmatch(key):
            raise ValueError(f"invalid environment variable name: {key!r}")
        if raw is None:
            normalized[key] = (None, None)
        elif isinstance(raw, str):
            _validate_value(key, raw)
            # A plain string enables a commented-out key in place.
            normalized[key] = (raw, True)
        elif isinstance(raw, dict):
            value = raw.get("value")
            enabled = raw.get("enabled")
            if value is not None and not isinstance(value, str):
                raise ValueError(f"update for {key} has a non-string value")
            if not isinstance(enabled, bool):
                raise ValueError(f"update for {key} must include a boolean 'enabled'")
            if value is not None:
                _validate_value(key, value)
            normalized[key] = (value, enabled)
        else:
            raise ValueError(
                f"update for {key} must be a string, null, or an object"
            )
    return normalized


def apply_env_updates(
    path: str | os.PathLike[str],
    updates: dict[str, Any],
    expected_mtime: float | None = None,
) -> dict[str, Any]:
    """Rewrite only the affected KEY=VALUE lines of an env file, in place.

    Unrelated lines (documentation comments, blanks, untouched entries)
    survive byte-identical. The original file is copied to ``<path>.bak``
    and the rewrite is atomic (tmp file + ``os.replace``). When
    ``expected_mtime`` is given, a stale read raises
    :class:`EnvFileConflictError` instead of overwriting newer content; the
    target is re-checked (mtime, inode, size) immediately before the replace
    to close the window between read and write.

    A labeled path may be a symlink (e.g. into a dotfiles checkout): reads,
    the backup, and the tmp+replace all operate on the resolved target in its
    own directory, so the symlink itself is never replaced. The result still
    reports the labeled path. The target's permission bits (and ownership,
    on platforms with ``os.chown``) are carried onto the replacement file.
    """
    labeled_path = Path(path)
    if not labeled_path.is_absolute():
        raise ValueError("env file path must be absolute")
    normalized = _normalized_updates(updates)

    file_path = Path(os.path.realpath(labeled_path))
    original_stat = os.stat(file_path)
    if expected_mtime is not None and original_stat.st_mtime != expected_mtime:
        raise EnvFileConflictError(
            f"{labeled_path} changed on disk since it was read"
        )
    text = file_path.read_text(encoding="utf-8")
    if len(text.encode("utf-8")) > _MAX_FILE_BYTES:
        raise ValueError("env file exceeds 256 KiB")
    entries = parse_env_file(text)
    if len(entries) > _MAX_ENTRIES:
        raise ValueError(f"env file cannot contain more than {_MAX_ENTRIES} entries")
    lines = text.splitlines(keepends=True)
    # Shell last-wins: a duplicated key's effective entry is its last active
    # assignment, or its last commented occurrence when none are active.
    by_key: dict[str, dict[str, Any]] = {}
    for entry in entries:
        existing = by_key.get(entry["key"])
        if existing is None or entry["enabled"] or not existing["enabled"]:
            by_key[entry["key"]] = entry

    updated: list[str] = []
    deleted: list[str] = []
    enabled_keys: list[str] = []
    appended: list[str] = []
    for key, (value, enabled) in normalized.items():
        entry = by_key.get(key)
        if value is None and enabled is None:
            if entry is None:
                raise ValueError(
                    f"cannot delete {key}: no such variable in the env file"
                )
            lines[entry["line"] - 1] = ""
            deleted.append(key)
            continue
        if entry is not None:
            index = entry["line"] - 1
            original = lines[index].rstrip("\r\n")
            newline = lines[index][len(original):]
            match = (_ACTIVE_LINE if entry["enabled"] else _COMMENTED_LINE).match(
                original,
            )
            indent = match.group("indent") if match else ""
            export = match.group("export") or "" if match else ""
            old_value, comment = _split_value(original[match.end():]) if match else ("", "")
            new_value = old_value if value is None else value
            marker = "" if enabled else "# "
            lines[index] = (
                f"{indent}{marker}{export}{key}={new_value}{comment}{newline}"
            )
            if enabled and not entry["enabled"]:
                enabled_keys.append(key)
            updated.append(key)
        else:
            marker = "" if enabled else "# "
            appended.append(f"{marker}{key}={value or ''}\n")
            if enabled:
                enabled_keys.append(key)
            updated.append(key)

    if appended:
        if lines and not lines[-1].endswith("\n"):
            lines[-1] = f"{lines[-1]}\n"
        lines.extend(appended)

    rendered = "".join(lines)
    if len(rendered.encode("utf-8")) > _MAX_FILE_BYTES:
        raise ValueError("updated env file would exceed 256 KiB")
    if len(parse_env_file(rendered)) > _MAX_ENTRIES:
        raise ValueError(
            f"updated env file would exceed {_MAX_ENTRIES} entries"
        )

    shutil.copy2(file_path, f"{file_path}.bak")
    tmp_path = f"{file_path}.tmp-{os.getpid()}"
    try:
        with open(tmp_path, "w", encoding="utf-8", newline="") as handle:
            handle.write(rendered)
        # A freshly created tmp file gets umask defaults; carry the target's
        # permission bits (and ownership where the platform supports chown)
        # so a restrictive env file stays restrictive after the replace.
        try:
            os.chmod(tmp_path, stat.S_IMODE(original_stat.st_mode))
            os.chown(tmp_path, original_stat.st_uid, original_stat.st_gid)
        except (AttributeError, PermissionError, OSError):
            pass
        current = os.stat(file_path)
        if (
            current.st_mtime != original_stat.st_mtime
            or current.st_ino != original_stat.st_ino
            or current.st_size != original_stat.st_size
        ):
            raise EnvFileConflictError(
                f"{labeled_path} changed on disk while it was being rewritten"
            )
        os.replace(tmp_path, file_path)
    finally:
        if os.path.exists(tmp_path):
            os.unlink(tmp_path)
    return {
        "path": str(labeled_path),
        "mtime": os.stat(file_path).st_mtime,
        "updated": updated,
        "deleted": deleted,
        "enabled": enabled_keys,
    }


def field_mapping(entries: list[dict[str, Any]]) -> dict[str, str]:
    """Map each editor control to its backing env key, when one exists."""
    present = {entry["key"] for entry in entries}
    mapping: dict[str, str] = {}
    for control, candidates in CONTROL_ENV_CANDIDATES.items():
        for candidate in candidates:
            if candidate in present:
                mapping[control] = candidate
                break
    return mapping


def resolve_control_updates(
    launch_controls: dict[str, Any] | None,
    gpu_memory_utilization: Any,
    served_model_name: Any,
    entries: list[dict[str, Any]],
) -> dict[str, str]:
    """Translate submitted editor controls into env-file value updates.

    Controls with a None value are skipped (None means "not submitted").
    Empty strings are skipped for every control except ``served_model_name``,
    where clearing the name is a real edit that writes ``SERVED_MODEL_NAME=``.
    A submitted control whose variable is absent from the env file is rejected
    with guidance, since the external start script only honors variables the
    file defines.
    """
    submitted: dict[str, Any] = dict(launch_controls or {})
    submitted["gpu_memory_utilization"] = gpu_memory_utilization
    submitted["served_model_name"] = served_model_name
    mapping = field_mapping(entries)
    updates: dict[str, str] = {}
    for control, value in submitted.items():
        if value is None or (value == "" and control != "served_model_name"):
            continue
        key = mapping.get(control)
        if key is None:
            candidates = CONTROL_ENV_CANDIDATES.get(control)
            if not candidates:
                raise ValueError(
                    f"launch control '{control}' cannot be edited through the "
                    "settings env file"
                )
            raise ValueError(
                f"the settings env file has no variable backing '{control}'; "
                f"add one of {', '.join(candidates)} to the file to edit it"
            )
        updates[key] = str(value)
    return updates
